#pmake: build trap remote os_zdos cpu_i86 cpu_386 ser x86
host_CPU = 386
host_OS = zdos

os = zdos
srv = ser
cpu = x86
which = TRAP

extra_objs = $(remote_objs) serzdos.obj

!include $(trap_dir)/master.mif
