#pmake: build lcl os_linux cpu_386 trap x86
#
# Create the Linux std.trp
#
host_os  = linux
host_cpu = 386

os    = linux
srv   = lcl
cpu   = x86
which = TRAP

!include $(trap_dir)/lcl/linux/trap.mif
!include $(trap_dir)/master.mif
