
objs = &
addrmode &
allign &
callimpl &
datamix1 &
datamix2 &
jmpimpl &
jmpshrt &
lea &
lsxxx &
mseg &
opi8u &
plsintr &
proccall &
push &
retiret &
seg16 &
segatrep &
shift &
structdd &
tbyte &
testequ &
tst1

dev_objs = &
3dnow &
mmx &
irpexitm

!include ../test.mif
