
objs = &
allign &
datamix1 &
datamix2 &
jmpshrt &
lea &
lsxxx &
mseg &
opi8u &
plsintr &
proccall &
push &
retiret &
seg16 &
segatrep &
shift &
structdd &
tbyte &
testequ

dev_objs = &
irpexitm

!include ../test.mif
