
objs = &
allign &
datamix1 &
datamix2 &
jmpshrt &
mseg &
opi8u &
plsintr &
proccall &
retiret &
seg16 &
segatrep &
shift &
structdd &
tbyte &
testequ

dev_objs = &
irpexitm &
lea &
lsxxx

!include ../test.mif
