.686
.xmm
.model small

.code

    addps        xmm1,cs:[bx+di+10]
    addps        xmm1,cs:[ebx+2*eax+10]
    addps        xmm1,datao
    addps        xmm1,xmm6
    addss        xmm1,cs:[bx+di+10]
    addss        xmm1,cs:[ebx+2*eax+10]
    addss        xmm1,datad
    addss        xmm1,xmm6	
    andnps       xmm1,cs:[bx+di+10]
    andnps       xmm1,cs:[ebx+2*eax+10]
    andnps       xmm1,datao
    andnps       xmm1,xmm6
    andps        xmm1,cs:[bx+di+10]
    andps        xmm1,cs:[ebx+2*eax+10]
    andps        xmm1,datao
    andps        xmm1,xmm6
    cmpeqps      xmm1,cs:[bx+di+10]
    cmpeqps      xmm1,cs:[ebx+2*eax+10]
    cmpeqps      xmm1,dataq
    cmpeqps      xmm1,xmm6
    cmpeqss      xmm1,cs:[bx+di+10]
    cmpeqss      xmm1,cs:[ebx+2*eax+10]
    cmpeqss      xmm1,dataq
    cmpeqss      xmm1,xmm6
    cmpleps      xmm1,cs:[bx+di+10]
    cmpleps      xmm1,cs:[ebx+2*eax+10]
    cmpleps      xmm1,dataq
    cmpleps      xmm1,xmm6
    cmpless      xmm1,cs:[bx+di+10]
    cmpless      xmm1,cs:[ebx+2*eax+10]
    cmpless      xmm1,dataq
    cmpless      xmm1,xmm6
    cmpltps      xmm1,cs:[bx+di+10]
    cmpltps      xmm1,cs:[ebx+2*eax+10]
    cmpltps      xmm1,dataq
    cmpltps      xmm1,xmm6
    cmpltss      xmm1,cs:[bx+di+10]
    cmpltss      xmm1,cs:[ebx+2*eax+10]
    cmpltss      xmm1,dataq
    cmpltss      xmm1,xmm6
    cmpneqps     xmm1,cs:[bx+di+10]
    cmpneqps     xmm1,cs:[ebx+2*eax+10]
    cmpneqps     xmm1,dataq
    cmpneqps     xmm1,xmm6
    cmpneqss     xmm1,cs:[bx+di+10]
    cmpneqss     xmm1,cs:[ebx+2*eax+10]
    cmpneqss     xmm1,dataq
    cmpneqss     xmm1,xmm6
    cmpnleps     xmm1,cs:[bx+di+10]
    cmpnleps     xmm1,cs:[ebx+2*eax+10]
    cmpnleps     xmm1,dataq
    cmpnleps     xmm1,xmm6
    cmpnless     xmm1,cs:[bx+di+10]
    cmpnless     xmm1,cs:[ebx+2*eax+10]
    cmpnless     xmm1,dataq
    cmpnless     xmm1,xmm6
    cmpnltps     xmm1,cs:[bx+di+10]
    cmpnltps     xmm1,cs:[ebx+2*eax+10]
    cmpnltps     xmm1,dataq
    cmpnltps     xmm1,xmm6
    cmpnltss     xmm1,cs:[bx+di+10]
    cmpnltss     xmm1,cs:[ebx+2*eax+10]
    cmpnltss     xmm1,dataq
    cmpnltss     xmm1,xmm6
    cmpordps     xmm1,cs:[bx+di+10]
    cmpordps     xmm1,cs:[ebx+2*eax+10]
    cmpordps     xmm1,dataq
    cmpordps     xmm1,xmm6
    cmpordss     xmm1,cs:[bx+di+10]
    cmpordss     xmm1,cs:[ebx+2*eax+10]
    cmpordss     xmm1,dataq
    cmpordss     xmm1,xmm6
    cmpps        xmm1,cs:[bx+di+10],255
    cmpps        xmm1,cs:[ebx+2*eax+10],255
    cmpps        xmm1,dataq,255
    cmpps        xmm1,xmm6,255
    cmpss        xmm1,cs:[bx+di+10],255
    cmpss        xmm1,cs:[ebx+2*eax+10],255
    cmpss        xmm1,dataq,255
    cmpss        xmm1,xmm6,255
    cmpunordps   xmm1,cs:[bx+di+10]
    cmpunordps   xmm1,cs:[ebx+2*eax+10]
    cmpunordps   xmm1,dataq
    cmpunordps   xmm1,xmm6
    cmpunordss   xmm1,cs:[bx+di+10]
    cmpunordss   xmm1,cs:[ebx+2*eax+10]
    cmpunordss   xmm1,dataq
    cmpunordss   xmm1,xmm6
    comiss       xmm1,cs:[bx+di+10]
    comiss       xmm1,cs:[ebx+2*eax+10]
    comiss       xmm1,datao
    comiss       xmm1,xmm6
    cvtpi2ps     xmm1,cs:[bx+di+10]
    cvtpi2ps     xmm1,cs:[ebx+2*eax+10]
    cvtpi2ps     xmm1,dataq
    cvtpi2ps     xmm1,mm5
    cvtps2pi     mm2,cs:[bx+di+10]
    cvtps2pi     mm2,cs:[ebx+2*eax+10]
    cvtps2pi     mm2,dataq
    cvtps2pi     mm2,xmm6
    cvtsi2ss     xmm1,cs:[bx+di+10]
    cvtsi2ss     xmm1,cs:[ebx+2*eax+10]
    cvtsi2ss     xmm1,datad
    cvtsi2ss     xmm1,ebx
    cvtss2si     ebx,cs:[bx+di+10]
    cvtss2si     ebx,cs:[ebx+2*eax+10]
    cvtss2si     ebx,datad
    cvtss2si     ebx,xmm4
    cvttps2pi    mm2,cs:[bx+di+10]
    cvttps2pi    mm2,cs:[ebx+2*eax+10]
    cvttps2pi    mm2,dataq
    cvttps2pi    mm2,xmm6
    cvttss2si    ebx,cs:[bx+di+10]
    cvttss2si    ebx,cs:[ebx+2*eax+10]
    cvttss2si    ebx,datad
    cvttss2si    ebx,xmm4
    divps        xmm1,cs:[bx+di+10]
    divps        xmm1,cs:[ebx+2*eax+10]
    divps        xmm1,dataq
    divps        xmm1,xmm6
    divss        xmm1,cs:[bx+di+10]
    divss        xmm1,cs:[ebx+2*eax+10]
    divss        xmm1,dataq
    divss        xmm1,xmm6
    fxrstor      cs:[bx+di+10]
    fxrstor      cs:[ebx+2*eax+10]
    fxrstor      dataq
    fxsave       cs:[bx+di+10]
    fxsave       cs:[ebx+2*eax+10]
    fxsave       dataq
    ldmxcsr      cs:[bx+di+10]
    ldmxcsr      cs:[ebx+2*eax+10]
    ldmxcsr      datad
    maskmovq     mm1,mm3
    maxps        xmm1,cs:[bx+di+10]
    maxps        xmm1,cs:[ebx+2*eax+10]
    maxps        xmm1,dataq
    maxps        xmm1,xmm6
    maxss        xmm1,cs:[bx+di+10]
    maxss        xmm1,cs:[ebx+2*eax+10]
    maxss        xmm1,dataq
    maxss        xmm1,xmm6
    minps        xmm1,cs:[bx+di+10]
    minps        xmm1,cs:[ebx+2*eax+10]
    minps        xmm1,dataq
    minps        xmm1,xmm6
    minss        xmm1,cs:[bx+di+10]
    minss        xmm1,cs:[ebx+2*eax+10]
    minss        xmm1,dataq
    minss        xmm1,xmm6
    movaps       cs:[bx+di+10],xmm7
    movaps       cs:[ebx+2*eax+10],xmm7
    movaps       dataq,xmm7
    movaps       xmm1,cs:[bx+di+10]
    movaps       xmm1,cs:[ebx+2*eax+10]
    movaps       xmm1,dataq
    movaps       xmm1,xmm6
    movhlps      xmm7,xmm1
    movhps       cs:[bx+di+10],xmm7
    movhps       cs:[ebx+2*eax+10],xmm7
    movhps       dataq,xmm7
    movhps       xmm1,cs:[bx+di+10]
    movhps       xmm1,cs:[ebx+2*eax+10]
    movhps       xmm1,dataq
    movlhps      xmm1,xmm7
    movlps       cs:[bx+di+10],xmm7
    movlps       cs:[ebx+2*eax+10],xmm7
    movlps       dataq,xmm7
    movlps       xmm7,cs:[bx+di+10]
    movlps       xmm7,cs:[ebx+2*eax+10]
    movlps       xmm7,dataq
    movmskps     ebx,xmm7
    movntps      cs:[bx+di+10],xmm7
    movntps      cs:[ebx+2*eax+10],xmm7
    movntps      dataq,xmm7
    movntq       cs:[bx+di+10],mm3
    movntq       cs:[ebx+2*eax+10],mm3
    movntq       dataq,mm3
    movss        cs:[bx+di+10],xmm7
    movss        cs:[ebx+2*eax+10],xmm7
    movss        dataq,xmm7
    movss        xmm1,cs:[bx+di+10]
    movss        xmm1,cs:[ebx+2*eax+10]
    movss        xmm1,dataq
    movss        xmm1,xmm6
    movups       cs:[bx+di+10],xmm7
    movups       cs:[ebx+2*eax+10],xmm7
    movups       dataq,xmm7
    movups       xmm1,cs:[bx+di+10]
    movups       xmm1,cs:[ebx+2*eax+10]
    movups       xmm1,dataq
    movups       xmm1,xmm6
    mulps        xmm1,cs:[bx+di+10]
    mulps        xmm1,cs:[ebx+2*eax+10]
    mulps        xmm1,dataq
    mulps        xmm1,xmm6
    mulss        xmm1,cs:[bx+di+10]
    mulss        xmm1,cs:[ebx+2*eax+10]
    mulss        xmm1,dataq
    mulss        xmm1,xmm6
    orps         xmm1,cs:[bx+di+10]
    orps         xmm1,cs:[ebx+2*eax+10]
    orps         xmm1,dataq
    orps         xmm1,xmm6
    pavgb        mm2,cs:[bx+di+10]
    pavgb        mm2,cs:[ebx+2*eax+10]
    pavgb        mm2,dataq
    pavgb        mm2,mm5
    pavgw        mm2,cs:[bx+di+10]
    pavgw        mm2,cs:[ebx+2*eax+10]
    pavgw        mm2,dataq
    pavgw        mm2,mm5
    pextrw       ebx,mm3,255
    pextrw       ebx,xmm3,255
    pinsrw       mm1,cs:[bx+di+10],255
    pinsrw       mm1,cs:[ebx+2*eax+10],255
    pinsrw       mm1,dataw,255
    pinsrw       mm3,ebx,255
    pinsrw       xmm1,cs:[bx+di+10],255
    pinsrw       xmm1,cs:[ebx+2*eax+10],255
    pinsrw       xmm1,dataw,255
    pinsrw       xmm3,ebx,255
    pmaxsw       mm2,cs:[bx+di+10]
    pmaxsw       mm2,cs:[ebx+2*eax+10]
    pmaxsw       mm2,dataq
    pmaxsw       mm2,mm5
    pmaxub       mm2,cs:[bx+di+10]
    pmaxub       mm2,cs:[ebx+2*eax+10]
    pmaxub       mm2,dataq
    pmaxub       mm2,mm5
    pminsw       mm2,cs:[bx+di+10]
    pminsw       mm2,cs:[ebx+2*eax+10]
    pminsw       mm2,dataq
    pminsw       mm2,mm5
    pminub       mm2,cs:[bx+di+10]
    pminub       mm2,cs:[ebx+2*eax+10]
    pminub       mm2,dataq
    pminub       mm2,mm5
    pmovmskb     ebx,mm1
    pmulhuw      mm1,cs:[bx+di+10]
    pmulhuw      mm1,cs:[ebx+2*eax+10]
    pmulhuw      mm1,dataq
    pmulhuw      mm1,mm6
    prefetchnta  cs:[bx+di+10]
    prefetchnta  cs:[ebx+2*eax+10]
    prefetchnta  dataq
    prefetcht0   cs:[bx+di+10]
    prefetcht0   cs:[ebx+2*eax+10]
    prefetcht0   dataq
    prefetcht1   cs:[bx+di+10]
    prefetcht1   cs:[ebx+2*eax+10]
    prefetcht1   dataq
    prefetcht2   cs:[bx+di+10]
    prefetcht2   cs:[ebx+2*eax+10]
    prefetcht2   dataq
    psadbw       mm2,cs:[bx+di+10]
    psadbw       mm2,cs:[ebx+2*eax+10]
    psadbw       mm2,dataq
    psadbw       mm2,mm5
    pshufw       mm2,cs:[bx+di+10],255
    pshufw       mm2,cs:[ebx+2*eax+10],255
    pshufw       mm2,dataq,255
    pshufw       mm2,mm5,255
    rcpps        xmm1,cs:[bx+di+10]
    rcpps        xmm1,cs:[ebx+2*eax+10]
    rcpps        xmm1,dataq
    rcpps        xmm1,xmm6
    rcpss        xmm1,cs:[bx+di+10]
    rcpss        xmm1,cs:[ebx+2*eax+10]
    rcpss        xmm1,dataq
    rcpss        xmm1,xmm6
    rsqrtps      xmm1,cs:[bx+di+10]
    rsqrtps      xmm1,cs:[ebx+2*eax+10]
    rsqrtps      xmm1,dataq
    rsqrtps      xmm1,xmm6
    rsqrtss      xmm1,cs:[bx+di+10]
    rsqrtss      xmm1,cs:[ebx+2*eax+10]
    rsqrtss      xmm1,dataq
    rsqrtss      xmm1,xmm6
    sfence
    shufps       xmm1,cs:[bx+di+10],255
    shufps       xmm1,cs:[ebx+2*eax+10],255
    shufps       xmm1,dataq,255
    shufps       xmm1,xmm6,255
    sqrtps       xmm1,cs:[bx+di+10]
    sqrtps       xmm1,cs:[ebx+2*eax+10]
    sqrtps       xmm1,dataq
    sqrtps       xmm1,xmm6
    sqrtss       xmm1,cs:[bx+di+10]
    sqrtss       xmm1,cs:[ebx+2*eax+10]
    sqrtss       xmm1,dataq
    sqrtss       xmm1,xmm6
    stmxcsr      cs:[bx+di+10]
    stmxcsr      cs:[ebx+2*eax+10]
    stmxcsr      datad
    subps        xmm1,cs:[bx+di+10]
    subps        xmm1,cs:[ebx+2*eax+10]
    subps        xmm1,dataq
    subps        xmm1,xmm6
    subss        xmm1,cs:[bx+di+10]
    subss        xmm1,cs:[ebx+2*eax+10]
    subss        xmm1,dataq
    subss        xmm1,xmm6
    ucomiss      xmm1,cs:[bx+di+10]
    ucomiss      xmm1,cs:[ebx+2*eax+10]
    ucomiss      xmm1,datao
    ucomiss      xmm1,xmm6
    unpckhps     xmm1,cs:[bx+di+10]
    unpckhps     xmm1,cs:[ebx+2*eax+10]
    unpckhps     xmm1,dataq
    unpckhps     xmm1,xmm6
    unpcklps     xmm1,cs:[bx+di+10]
    unpcklps     xmm1,cs:[ebx+2*eax+10]
    unpcklps     xmm1,dataq
    unpcklps     xmm1,xmm6
    xorps        xmm1,cs:[bx+di+10]
    xorps        xmm1,cs:[ebx+2*eax+10]
    xorps        xmm1,dataq
    xorps        xmm1,xmm6
    
.data

datao label oword
dataq dq 0
datad dd 0
dataw dw 0

end
