#pmake: build trap remote os_os2 cpu_i86 cpu_386 tcp x86

host_os  = os2
host_cpu = 386

os    = os2v2
srv   = tcp
cpu   = x86
which = TRAP
type  = remote_link

extra_libs = $(os2386)

!include $(trap_dir)/master.mif
