#pmake: build serv remote os_win cpu_i86 cpu_386 vdm x86
host_CPU = i86
host_OS = win

gui = 1
os = win
srv = vdm
cpu = x86
which = SERVER
type  = remote_link

>>>> ORIGINAL makefile#1
extra_objs = $(remote_objs) vdmserv.obj
resource_file = serv.res
==== THEIRS makefile#8
extra_objs = vdmserv.obj
==== YOURS makefile
extra_objs = $(remote_objs) vdmserv.obj
<<<<

!include $(trap_dir)/master.mif
